name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package.json
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "has_pkg=true" >> $GITHUB_OUTPUT
          else
            echo "has_pkg=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        if: steps.detect.outputs.has_pkg == 'true'
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: steps.detect.outputs.has_pkg == 'true'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Type check
        if: steps.detect.outputs.has_pkg == 'true'
        run: npm run typecheck --if-present

      - name: Lint
        if: steps.detect.outputs.has_pkg == 'true'
        run: npm run lint --if-present

      - name: Format check
        if: steps.detect.outputs.has_pkg == 'true'
        run: npm run format --if-present

      - name: Unit tests
        if: steps.detect.outputs.has_pkg == 'true'
        run: npm test --if-present

      - name: Build
        if: steps.detect.outputs.has_pkg == 'true'
        run: npm run build --if-present
